server:
  port: 6222

spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:orders_db
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true